import argparse
import sys
import pandas as pd
import numpy as np
from pathlib import Path

parser = argparse.ArgumentParser(description="Source Classification v2")
parser.add_argument("--region", required=True, help="Region ID")
args = parser.parse_args()

sys.path.insert(0, str(Path(".").resolve()))
from config.regions import get_region
_region = get_region(args.region)

FIRMS_FILE  = _region["analysis_dir"] / "thermal_events.csv"
OSM_FILE    = _region["industry_dir"] / _region["osm_csv_file"]
WC_FILE     = _region["analysis_dir"] / "thermal_worldcover_context.csv"
OSM_ASSOC_FILE = _region["analysis_dir"] / "historical_thermal_osm_association.csv"
OUTPUT_FILE = _region["analysis_dir"] / "thermal_source_classification_v2.csv"
_REGION_ID  = args.region


# ------------------------------------------------------------
# 1. Load data
# ------------------------------------------------------------

print("=" * 70)
print("SIH26162 — Source Classification v2")
print("=" * 70)

print("\nLoading FIRMS observations...")
firms = pd.read_csv(FIRMS_FILE)

print(f"FIRMS observations: {len(firms)}")

print("\nLoading OSM industrial evidence...")
osm = pd.read_csv(OSM_FILE)

print(f"OSM features: {len(osm)}")

print("\nLoading WorldCover context...")
wc = pd.read_csv(WC_FILE)

print(f"WorldCover records: {len(wc)}")


# ------------------------------------------------------------
# 2. Use Event ID as key
# ------------------------------------------------------------

if "event_id" not in firms.columns:
    raise ValueError("Missing event_id in thermal_events.csv")
    
if "event_id" not in wc.columns:
    raise ValueError("Missing event_id in thermal_worldcover_context.csv")


# ------------------------------------------------------------
# 3. Inspect WorldCover fields
# ------------------------------------------------------------

print("\nWorldCover columns:")
print(list(wc.columns))

# Expected column from sample_worldcover.py:
# landcover_class
#
# If the script used another name, detect it automatically.

possible_wc_columns = [
    "landcover_class",
    "worldcover_class",
    "class_name",
    "class",
]

wc_class_col = None

for col in possible_wc_columns:
    if col in wc.columns:
        wc_class_col = col
        break

if wc_class_col is None:
    raise ValueError(
        "Could not find WorldCover class column. "
        "Expected one of: "
        + ", ".join(possible_wc_columns)
    )

print(f"Using WorldCover class column: {wc_class_col}")


# ------------------------------------------------------------
# 4. Join WorldCover context to FIRMS
# ------------------------------------------------------------

wc_context = wc[["event_id", wc_class_col]].copy()

wc_context = wc_context.rename(
    columns={wc_class_col: "worldcover_class"}
)

df = firms.merge(
    wc_context,
    on="event_id",
    how="left",
)

missing_wc = df["worldcover_class"].isna().sum()

print(f"\nWorldCover matches: {len(df) - missing_wc}/{len(df)}")
print(f"WorldCover missing: {missing_wc}")


# ------------------------------------------------------------
# 5. Normalize OSM fields
# ------------------------------------------------------------

osm.columns = [str(c).strip().lower() for c in osm.columns]

print("\nNormalized OSM columns:")
print(list(osm.columns))


def find_column(candidates):
    for c in candidates:
        if c in osm.columns:
            return c
    return None


name_col = find_column([
    "name",
    "name_en",
])

industrial_col = find_column([
    "industrial",
])

landuse_col = find_column([
    "landuse",
])

power_col = find_column([
    "power",
])

amenity_col = find_column([
    "amenity",
])


for col in [
    name_col,
    industrial_col,
    landuse_col,
    power_col,
    amenity_col,
]:
    if col is not None:
        osm[col] = osm[col].fillna("").astype(str).str.lower()


# ------------------------------------------------------------
# 6. Build OSM evidence score
# ------------------------------------------------------------
#
# This section intentionally uses the existing v1 association
# logic as the industrial-context signal.
#
# Geometry/distance columns may already exist in the OSM CSV.
# We therefore try to find them rather than assuming names.
# ------------------------------------------------------------

# The OSM CSV generated by download_osm_industry.py may contain
# geometry information but not necessarily metric distance.
#
# For v2 we use the already-computed v1 classification as the
# strongest industrial evidence whenever available.
#
# Therefore locate v1 output.

V1_FILE = _region["analysis_dir"] / "thermal_source_classification.csv"

if not V1_FILE.exists():
    raise FileNotFoundError(
        f"v1 classification not found:\n{V1_FILE}\n"
        "Run calculate_source_classification.py first."
    )

print("\nLoading v1 industrial evidence...")
v1 = pd.read_csv(V1_FILE)

if "event_id" not in v1.columns:
    raise ValueError("Missing event_id in v1 classification")

v1_cols = [
    "event_id"
]

# Preserve useful v1 fields if present
for col in [
    "source_class",
    "classification",
    "confidence",
    "evidence_score",
    "industrial_evidence_score",
    "nearest_feature",
    "osm_feature",
]:
    if col in v1.columns:
        v1_cols.append(col)

v1_small = v1[v1_cols].copy()

# Avoid collisions with existing FIRMS columns
rename_map = {}

for col in v1_small.columns:
    if col != "event_id" and col in df.columns:
        rename_map[col] = f"v1_{col}"

v1_small = v1_small.rename(columns=rename_map)

df = df.merge(
    v1_small,
    on="event_id",
    how="left",
)


# ------------------------------------------------------------
# 7. Normalize v1 classification
# ------------------------------------------------------------

# Find the actual v1 class field
v1_class_col = None

for col in [
    "source_class",
    "classification",
    "v1_source_class",
    "v1_classification",
]:
    if col in df.columns:
        v1_class_col = col
        break

if v1_class_col is None:
    raise ValueError(
        "Could not find source classification field in v1 output."
    )

df[v1_class_col] = (
    df[v1_class_col]
    .fillna("")
    .astype(str)
    .str.upper()
)


# ------------------------------------------------------------
# 8. WorldCover category groups
# ------------------------------------------------------------

def normalize_wc(value):
    if pd.isna(value):
        return "UNKNOWN"

    value = str(value).strip().upper()

    # Forest / natural vegetation
    if value in {
        "TREE_COVER",
        "SHRUBLAND",
        "GRASSLAND",
        "HERBACEOUS_WETLAND",
        "MANGROVES",
        "MOSS_LICHEN",
    }:
        return "NATURAL"

    # Agricultural
    if value == "CROPLAND":
        return "AGRICULTURAL"

    # Built environment
    if value == "BUILT_UP":
        return "BUILT_UP"

    # Other non-vegetation
    if value in {
        "BARE_SPARSE_VEGETATION",
        "PERMANENT_WATER_BODIES",
        "SNOW_ICE",
    }:
        return "OTHER"

    return "UNKNOWN"


df["worldcover_context"] = df["worldcover_class"].apply(
    normalize_wc
)


# ------------------------------------------------------------
# 9. Source classification decision logic
# ------------------------------------------------------------
#
# We deliberately avoid pretending that WorldCover alone can
# classify a thermal event.
#
# Priority:
#
# 1. Strong OSM industrial evidence
#       -> INDUSTRIAL_ASSOCIATED
#
# 2. No industrial evidence + CROPLAND
#       -> AGRICULTURAL
#
# 3. No industrial evidence + natural vegetation
#       -> FOREST_NATURAL
#
# 4. No industrial evidence + other land cover
#       -> OTHER
#
# 5. Missing/ambiguous evidence
#       -> UNKNOWN
#
# IMPORTANT:
# "INDUSTRIAL_ASSOCIATED" means spatially associated with
# industrial infrastructure. It does NOT mean confirmed fire.
# ------------------------------------------------------------

def classify(row):

    v1_class = str(row[v1_class_col]).upper().strip()

    wc_context = row["worldcover_context"]

    # --------------------------------------------------------
    # Industrial evidence has priority.
    # --------------------------------------------------------

    if "INDUSTRIAL_ASSOCIATED" in v1_class:
        return "INDUSTRIAL_ASSOCIATED"

    # Some versions may use just INDUSTRIAL
    if v1_class == "INDUSTRIAL":
        return "INDUSTRIAL_ASSOCIATED"

    # --------------------------------------------------------
    # WorldCover contextual classification
    # --------------------------------------------------------

    if wc_context == "AGRICULTURAL":
        return "AGRICULTURAL"

    if wc_context == "NATURAL":
        return "FOREST_NATURAL"

    if wc_context == "OTHER":
        return "OTHER"

    if wc_context == "BUILT_UP":
        # Built-up alone is NOT enough to call something industrial.
        return "UNKNOWN"

    return "UNKNOWN"


df["source_class_v2"] = df.apply(
    classify,
    axis=1,
)


# ------------------------------------------------------------
# 10. Confidence / evidence explanation
# ------------------------------------------------------------

def evidence_level(row):

    v1_class = str(row[v1_class_col]).upper().strip()
    wc = row["worldcover_context"]

    if "INDUSTRIAL_ASSOCIATED" in v1_class:
        if wc == "BUILT_UP":
            return "HIGH"

        return "MEDIUM"

    if wc in {
        "AGRICULTURAL",
        "NATURAL",
    }:
        return "MEDIUM"

    if wc == "OTHER":
        return "LOW"

    return "LOW"


df["classification_confidence_v2"] = df.apply(
    evidence_level,
    axis=1,
)


def evidence_reason(row):

    v1_class = str(row[v1_class_col]).upper().strip()
    wc = row["worldcover_context"]

    if "INDUSTRIAL_ASSOCIATED" in v1_class:

        if wc == "BUILT_UP":
            return (
                "OSM industrial association + built-up "
                "WorldCover context"
            )

        return (
            "OSM industrial association; WorldCover "
            f"context={wc}"
        )

    if wc == "AGRICULTURAL":
        return (
            "No strong OSM industrial association; "
            "WorldCover indicates cropland"
        )

    if wc == "NATURAL":
        return (
            "No strong OSM industrial association; "
            "WorldCover indicates natural vegetation"
        )

    if wc == "OTHER":
        return (
            "No strong OSM industrial association; "
            f"WorldCover context={row['worldcover_class']}"
        )

    if wc == "BUILT_UP":
        return (
            "Built-up context detected, but no strong "
            "industrial evidence"
        )

    return "Insufficient contextual evidence"


df["classification_reason"] = df.apply(
    evidence_reason,
    axis=1,
)


# ------------------------------------------------------------
# 11. Add persistence-independent source interpretation
# ------------------------------------------------------------

df["interpretation"] = ""

df.loc[
    df["source_class_v2"] == "INDUSTRIAL_ASSOCIATED",
    "interpretation"
] = (
    "Thermal observation spatially associated with "
    "industrial infrastructure"
)

df.loc[
    df["source_class_v2"] == "AGRICULTURAL",
    "interpretation"
] = (
    "Thermal observation occurs in cropland context; "
    "agricultural/biomass source is plausible"
)

df.loc[
    df["source_class_v2"] == "FOREST_NATURAL",
    "interpretation"
] = (
    "Thermal observation occurs in natural vegetation "
    "context; natural/vegetation source is plausible"
)

df.loc[
    df["source_class_v2"] == "OTHER",
    "interpretation"
] = (
    "Thermal observation has no strong industrial association "
    "and occurs in another land-cover context"
)

df.loc[
    df["source_class_v2"] == "UNKNOWN",
    "interpretation"
] = (
    "Available contextual evidence is insufficient for "
    "reliable source classification"
)


# ------------------------------------------------------------
# 12. Add OSM evidence fields
# ------------------------------------------------------------

# Load the authoritative OSM association result so the final
# classification can explain which mapped feature supported it.

OSM_ASSOC_FILE = (
    _region["analysis_dir"] / "historical_thermal_osm_association.csv"
)

if not OSM_ASSOC_FILE.exists():
    raise FileNotFoundError(
        f"OSM association file not found:\n{OSM_ASSOC_FILE}"
    )

print("\nLoading OSM association evidence...")

osm_assoc = pd.read_csv(OSM_ASSOC_FILE)

if "event_id" not in osm_assoc.columns:
    raise ValueError("Missing event_id in OSM association data")

osm_evidence_cols = [
    "event_id",
    "association_type",
    "association_confidence",
    "osm_type",
    "osm_id",
    "name",
    "industrial",
    "landuse",
    "power",
    "man_made",
    "distance_km",
]

osm_evidence_cols = [
    c for c in osm_evidence_cols
    if c in osm_assoc.columns
]

osm_small = osm_assoc[osm_evidence_cols].copy()

# Avoid duplicate column names after merge.
rename_map = {}

for col in osm_small.columns:
    if col != "event_id" and col in df.columns:
        rename_map[col] = f"assoc_{col}"

osm_small = osm_small.rename(columns=rename_map)

df = df.merge(
    osm_small,
    on="event_id",
    how="left",
)

# ------------------------------------------------------------
# 13. Clean OSM evidence fields
# ------------------------------------------------------------

def clean_text(value):
    if pd.isna(value):
        return ""
    return str(value).strip()


for col in [
    "name",
    "industrial",
    "landuse",
    "power",
    "man_made",
    "association_type",
    "association_confidence",
]:
    if col in df.columns:
        df[col] = df[col].apply(clean_text)


# ------------------------------------------------------------
# 14. Final evidence strength
# ------------------------------------------------------------

def evidence_strength(row):

    assoc = row.get("association_type", "")
    confidence = row.get("association_confidence", "")
    wc = row["worldcover_context"]

    # Direct geometry intersection with mapped OSM feature
    if assoc == "OSM_FEATURE_INTERSECTION":
        if wc == "BUILT_UP":
            return "VERY_HIGH"

        return "HIGH"

    # Nearby feature, but not intersecting
    if assoc == "NEARBY_OSM_INDUSTRIAL_FEATURE":
        return "MEDIUM"

    # WorldCover-only contextual evidence
    if wc in {
        "AGRICULTURAL",
        "NATURAL",
    }:
        return "MEDIUM"

    if wc == "OTHER":
        return "LOW"

    return "LOW"


df["evidence_strength"] = df.apply(
    evidence_strength,
    axis=1,
)


# ------------------------------------------------------------
# 15. Human-readable evidence summary
# ------------------------------------------------------------

def build_evidence_summary(row):

    source = row["source_class_v2"]
    wc = row["worldcover_class"]

    assoc = row.get("association_type", "")
    name = row.get("name", "")
    distance = row.get("distance_km", np.nan)

    if source == "INDUSTRIAL_ASSOCIATED":

        if assoc == "OSM_FEATURE_INTERSECTION":

            if name:
                return (
                    f"Thermal point intersects mapped industrial "
                    f"feature: {name}; WorldCover={wc}"
                )

            return (
                "Thermal point intersects mapped industrial "
                f"feature; WorldCover={wc}"
            )

        if assoc == "NEARBY_OSM_INDUSTRIAL_FEATURE":

            if name and pd.notna(distance):
                return (
                    f"Thermal point is {distance:.3f} km from "
                    f"mapped industrial feature: {name}; "
                    f"WorldCover={wc}"
                )

            return (
                "Thermal point is near mapped industrial "
                f"feature; WorldCover={wc}"
            )

    if source == "AGRICULTURAL":
        return (
            "No strong mapped industrial association; "
            f"WorldCover={wc}"
        )

    if source == "FOREST_NATURAL":
        return (
            "No strong mapped industrial association; "
            f"WorldCover={wc}"
        )

    if source == "OTHER":
        return (
            "No strong mapped industrial association; "
            f"WorldCover={wc}"
        )

    return "Insufficient evidence"


df["evidence_summary"] = df.apply(
    build_evidence_summary,
    axis=1,
)


# ------------------------------------------------------------
# 16. Select final output columns
# ------------------------------------------------------------

preferred_columns = [
    # Event Fields
    "event_id",
    "event_date",
    "event_start_time",
    "event_end_time",
    "observation_count",
    "satellite_count",
    "satellites",
    "max_frp",
    "total_frp",
    "mean_frp",
    
    # Coordinates
    "latitude",
    "longitude",

    # WorldCover
    "worldcover_class",
    "worldcover_context",

    # OSM evidence
    "association_type",
    "association_confidence",
    "osm_type",
    "osm_id",
    "name",
    "industrial",
    "landuse",
    "power",
    "man_made",
    "distance_km",

    # Classification
    v1_class_col,
    "source_class_v2",
    "classification_confidence_v2",
    "evidence_strength",
    "classification_reason",
    "evidence_summary",
    "interpretation",
]

output_columns = []

for col in preferred_columns:
    if col in df.columns and col not in output_columns:
        output_columns.append(col)

result = df[output_columns].copy()


# ------------------------------------------------------------
# 17. Save
# ------------------------------------------------------------

OUTPUT_FILE.parent.mkdir(
    parents=True,
    exist_ok=True,
)

result.to_csv(
    OUTPUT_FILE,
    index=False,
)


# ------------------------------------------------------------
# 18. Validation
# ------------------------------------------------------------

print("\n" + "=" * 70)
print("V2 CLASSIFICATION SUMMARY")
print("=" * 70)

print(
    result["source_class_v2"]
    .value_counts(dropna=False)
    .to_string()
)

print("\nEvidence strength:")
print(
    result["evidence_strength"]
    .value_counts(dropna=False)
    .to_string()
)

print("\nOSM association type:")
print(
    result["association_type"]
    .value_counts(dropna=False)
    .to_string()
)

print("\nWorldCover context:")
print(
    result["worldcover_context"]
    .value_counts(dropna=False)
    .to_string()
)

print("\nIndustrial-associated OSM features:")

industrial_result = result[
    result["source_class_v2"] == "INDUSTRIAL_ASSOCIATED"
]

if len(industrial_result) > 0:

    feature_counts = (
        industrial_result["name"]
        .replace("", "UNNAMED")
        .fillna("UNNAMED")
        .value_counts()
        .head(15)
    )

    print(feature_counts.to_string())

print("\nCross-tab: source class vs WorldCover context")

print(
    pd.crosstab(
        result["source_class_v2"],
        result["worldcover_context"],
        margins=True,
    )
)

print("\nOutput:")
print(OUTPUT_FILE)

print("\nDone.")